### PR TITLE
new word "paradigm"

### PR DESCRIPTION
**Pull request by ggeorgovassilis**

### CODE REVIEW

**Comment by tsevdos** [comment]
Goos one but it's not so "techy", don't you agree?

**Comment by ggeorgovassilis** [comment]
Not any more or less than Pseudo or Parameter which are in the current corpus

**Comment by tsevdos** [comment]
Maybe you are right, I'll get back to you tomorrow. FYI: the module is already up https://www.npmjs.com/package/greek-in-tech although I need to update it, to see your contributions (I'll do it someday this week)....

**Comment by ggeorgovassilis** [comment]
You over-estimate my interest in this :-)

**Pull request closed without merging**
